### ISSUE TITLE
Changing build.publicPath leads to broken links in css files

### ISSUE THREAD

**Issue by mefcorvi** [koumoul-dev/nuxt-config-inject#3]
Hello,

Thank you for your work on this package, we spent few days trying to work around this build-time configuration nonsense until we've found your package.

We use this package to override build.publicPath at runtime because we need to use CDN only in production environment. Everything works as a charm except web fonts. By some reason, URLs in the generated css files are lowercased, i.e. they look like `https://startconfigalias-string-publicpath-endconfigalias/fonts/f3501dc.woff2`. Lowercasing makes sense since DNS is case-insensitive, but this brakes case-sensitive replacement logic.

Was `RegExp('(\'|"|http://|https://|/)?STARTCONFIGALIAS-(.*?)-(.*?)-ENDCONFIGALIAS(\'|"|/)?', 'gm')` intentionally made case-sensitive?

Thank you,
Bulat Aykaev.

**Comment by albanm** [comment]
Hello,

No, upper case was mostly for confort, it sticks out better in large texts and was easier to spot by eye when debugging stuff. And I simply didn't think of making the regexp case insensitive.

I suppose adding the 'i' flag to the regexp would be enough to solve your problem ?

**Comment by mefcorvi** [comment]
Yes, the 'i' flag shall help.

**Comment by albanm** [comment]
I just released v0.4.4 with this modification.

**Comment by mefcorvi** [comment]
Thank you! Overriding works fine.

**Comment by mefcorvi** [comment]
After some investigation I must admit that the issue is not fully resolved.
The regular expression is also used to get name of the key, but that key is also lowercased. In our case we have `https://startconfigalias-string-publicpath-endconfigalias/fonts/012cf6a.woff` in the css file and the `replace` function replaces `https://startconfigalias-string-publicpath-endconfigalias/` by `/` because `publicpath` key doesn't exist in the passed config object.
